import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./main.css";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={cn("font-sans", inter.variable)}>
      <head>
        <template
          id="theme-script"
          dangerouslySetInnerHTML={{
            __html: `
              <script>
                (function () {
                  try {
                    const theme = localStorage.getItem("theme");
                    if (theme === "dark") {
                      document.documentElement.classList.add("dark");
                    } else {
                      document.documentElement.classList.remove("dark");
                    }
                  } catch (e) {}
                })();
              </script>
            `,
          }}
        />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              // This immediately runs and executes the script inside the template above
              const template = document.getElementById('theme-script');
              if (template) {
                document.head.appendChild(template.content.cloneNode(true));
              }
            `,
          }}
        />
      </head>
      <body
        className="font-poppins text-auto"
      >
        {children}
      </body>
    </html>
  );
}
